require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe Admin::GitUpdatesController do

  # This should return the minimal set of attributes required to create a valid
  # Admin::GitUpdate. As you add validations to Admin::GitUpdate, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "comment" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Admin::GitUpdatesController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all admin_git_updates as @admin_git_updates" do
      git_update = Admin::GitUpdate.create! valid_attributes
      get :index, {}, valid_session
      assigns(:admin_git_updates).should eq([git_update])
    end
  end

  describe "GET show" do
    it "assigns the requested admin_git_update as @admin_git_update" do
      git_update = Admin::GitUpdate.create! valid_attributes
      get :show, {:id => git_update.to_param}, valid_session
      assigns(:admin_git_update).should eq(git_update)
    end
  end

  describe "GET new" do
    it "assigns a new admin_git_update as @admin_git_update" do
      get :new, {}, valid_session
      assigns(:admin_git_update).should be_a_new(Admin::GitUpdate)
    end
  end

  describe "GET edit" do
    it "assigns the requested admin_git_update as @admin_git_update" do
      git_update = Admin::GitUpdate.create! valid_attributes
      get :edit, {:id => git_update.to_param}, valid_session
      assigns(:admin_git_update).should eq(git_update)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Admin::GitUpdate" do
        expect {
          post :create, {:admin_git_update => valid_attributes}, valid_session
        }.to change(Admin::GitUpdate, :count).by(1)
      end

      it "assigns a newly created admin_git_update as @admin_git_update" do
        post :create, {:admin_git_update => valid_attributes}, valid_session
        assigns(:admin_git_update).should be_a(Admin::GitUpdate)
        assigns(:admin_git_update).should be_persisted
      end

      it "redirects to the created admin_git_update" do
        post :create, {:admin_git_update => valid_attributes}, valid_session
        response.should redirect_to(Admin::GitUpdate.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved admin_git_update as @admin_git_update" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::GitUpdate.any_instance.stub(:save).and_return(false)
        post :create, {:admin_git_update => { "comment" => "invalid value" }}, valid_session
        assigns(:admin_git_update).should be_a_new(Admin::GitUpdate)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::GitUpdate.any_instance.stub(:save).and_return(false)
        post :create, {:admin_git_update => { "comment" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested admin_git_update" do
        git_update = Admin::GitUpdate.create! valid_attributes
        # Assuming there are no other admin_git_updates in the database, this
        # specifies that the Admin::GitUpdate created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Admin::GitUpdate.any_instance.should_receive(:update_attributes).with({ "comment" => "MyString" })
        put :update, {:id => git_update.to_param, :admin_git_update => { "comment" => "MyString" }}, valid_session
      end

      it "assigns the requested admin_git_update as @admin_git_update" do
        git_update = Admin::GitUpdate.create! valid_attributes
        put :update, {:id => git_update.to_param, :admin_git_update => valid_attributes}, valid_session
        assigns(:admin_git_update).should eq(git_update)
      end

      it "redirects to the admin_git_update" do
        git_update = Admin::GitUpdate.create! valid_attributes
        put :update, {:id => git_update.to_param, :admin_git_update => valid_attributes}, valid_session
        response.should redirect_to(git_update)
      end
    end

    describe "with invalid params" do
      it "assigns the admin_git_update as @admin_git_update" do
        git_update = Admin::GitUpdate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::GitUpdate.any_instance.stub(:save).and_return(false)
        put :update, {:id => git_update.to_param, :admin_git_update => { "comment" => "invalid value" }}, valid_session
        assigns(:admin_git_update).should eq(git_update)
      end

      it "re-renders the 'edit' template" do
        git_update = Admin::GitUpdate.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Admin::GitUpdate.any_instance.stub(:save).and_return(false)
        put :update, {:id => git_update.to_param, :admin_git_update => { "comment" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested admin_git_update" do
      git_update = Admin::GitUpdate.create! valid_attributes
      expect {
        delete :destroy, {:id => git_update.to_param}, valid_session
      }.to change(Admin::GitUpdate, :count).by(-1)
    end

    it "redirects to the admin_git_updates list" do
      git_update = Admin::GitUpdate.create! valid_attributes
      delete :destroy, {:id => git_update.to_param}, valid_session
      response.should redirect_to(admin_git_updates_url)
    end
  end

end
